# Generated by Django 4.0.1 on 2022-01-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoshkacho', '0002_auto_20211028_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
